# .github/workflows/main.yml
# ... (jobs.build.steps まで)

    steps:
      # ... (npm install, build, and test ステップまで)

      - name: Zip artifact for deployment # .next/standalone ディレクトリ全体を圧縮
        run: |
          zip -r release.zip ./.next/standalone

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    # ... (deploy job の Download artifact, Unzip まで)
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-step4-30'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          startup-command: "node ./.next/standalone/server.js" # Next.js standalone の起動コマンド